### ISSUE TITLE
SyntaxError: invalid syntax for PaxHeader

### ISSUE THREAD

**Issue by danyeaw** [invent-framework/invent#133]
Hi, I created a new development environment using the README instructions. When I run `make serve` and open `localhost:8000`, I get the following traceback shown on the Invent page:

```
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "upytest.py", line 513, in run
  File "upytest.py", line 395, in discover
  File "upytest.py", line 97, in import_module
  File "tests/PaxHeader/__init__.py", line 1
SyntaxError: invalid syntax
```

This is with macOS 15.2 with Chrome with no extensions loaded.

**Comment by danyeaw** [comment]
If I install GNU Tar with `brew install gnu-tar` and then change the Makefile to:

	cd test_suite && gtar -czvf ../test_suite.tar.gz tests/* invent/*

To run gtar instead of BSD tar, the syntax error goes away.

**Comment by ntoll** [comment]
Thank you for the report and investigation.

I'm on Linux, and `gtar` is not a package available to me (I presume because `tar` on Linux is `gtar` on OSX). I guess we could document this, or (when untarring in PyScript) ensure such directories are deleted when extracted. On that latter point, we just use the tgz based capabilities of the underlying Python interpreter to make things work (Pyodide and MicroPython), so much of this behaviour will depend on their implementations of tar/gzip. Worth investigating further in the new year.

**Comment by mhsmith** [comment]
I'm seeing the same thing on macOS. It's probably because #130 changed the packaging format from .zip to .tar.gz.

**Comment by ntoll** [comment]
Yeah, we did this because MicroPython and Pyodide both natively support `.tgz` whereas only Pyodide supported `.zip`. When MicroPython encounters a `.zip` PyScript kicks in and provides a dynamically downloaded JS library to shim around the unzipping into the filesystem. This, of course, adds more time to PyScript start-up. Hence the change.
