### ISSUE TITLE
Address tech debt: use separator in name of datastore related keys (e.g. invent-foo)

### ISSUE THREAD

**Issue by ntoll** [invent-framework/invent#87]
Local storage keys are constructed as `invent` + key name. There should be a separator for readability. E.g. `invent-keyname`.

**Comment by mhsmith** [comment]
This appears to have broken a large number of unit tests:
```
FAILED tests/test_datastore.py::test_datastore_init_with_values - KeyError: '...
FAILED tests/test_datastore.py::test_datastore_namespace_key - AssertionError...
FAILED tests/test_datastore.py::test_datastore_copy - TypeError: the JSON obj...
FAILED tests/test_datastore.py::test_datastore_get_with_value - AssertionErro...
FAILED tests/test_datastore.py::test_datastore_items - TypeError: the JSON ob...
FAILED tests/test_datastore.py::test_datastore_keys - AssertionError: assert ...
FAILED tests/test_datastore.py::test_datastore_pop - assert None == 1
FAILED tests/test_datastore.py::test_datastore_setdefault_no_key - AssertionE...
FAILED tests/test_datastore.py::test_datastore_setdefault_has_key - Assertion...
FAILED tests/test_datastore.py::test_datastore_setdefault_no_key_with_default
FAILED tests/test_datastore.py::test_datastore_update - KeyError: 'a'
FAILED tests/test_datastore.py::test_datastore_values - TypeError: the JSON o...
FAILED tests/test_datastore.py::test_datastore_get_set_del_item - KeyError: 'a'
FAILED tests/test_datastore.py::test_datastore_contains - AssertionError: ass...
```

And also the farmyard example:
```
Traceback (most recent call last):
  File "<stdin>", line 105, in <module>
  File "invent/ui/core/component.py", line 583, in __init__
  File "invent/ui/core/component.py", line 157, in __init__
  File "invent/ui/core/component.py", line 185, in update
  File "invent/ui/core/property.py", line 141, in __set__
  File "<stdin>", line 43, in make_geese
TypeError: can't convert list to int
```

Line 43 is:
```py
    return [TextBox(text="🪿") for _ in range(number_of_honks)]
```

Which presumably means that `number_of_honks` has ended up as a list.
